name: identical_items_list

description: Efficient implementation of a non-empty list, iterable, and
  iterator containing identical elements.

version: 1.0.1

topics:
 - list
 - collection
 - iterator
 - iterable

repository: https://github.com/simphotonics/identical_items_list

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
