name: identical_items_list

description: Efficient implementation of a non-empty unmodifiable
 list and iterable containing identical elements.

version: 1.0.2

topics:
 - list
 - collection
 - iterator
 - iterable

repository: https://github.com/simphotonics/identical_items_list

environment:
  sdk: ^3.7.0

dev_dependencies:
  benchmark_runner: ^2.0.0
  lints: ^5.1.1
  test: ^1.24.0
