name: identical_items_list

description: Efficient non-empty unmodifiable
 list and iterable containing identical elements.

version: 1.0.3

topics:
 - list
 - iterable
 - iterator
 - collection

repository: https://github.com/simphotonics/identical_items_list

environment:
  sdk: ^3.9.0

dev_dependencies:
  benchmark_runner: ^2.0.2
  lints: ^6.0.0
  test: ^1.26.3
